import type { CategoryId } from "economy-simulator-data";

interface PersonalityProfile {
	openness: number;
	conscientiousness: number;
	extraversion: number;
	agreeableness: number;
	neuroticism: number;
}

const TRAITS = [
	"openness",
	"conscientiousness",
	"extraversion",
	"agreeableness",
	"neuroticism",
] as const satisfies readonly (keyof PersonalityProfile)[];

/**
 * Ideal-profile weights per economic category: +1 rewards a trait, -1
 * penalizes it, 0 is neutral. Sourced from Barrick & Mount (1991) and
 * Larson, Rottinghaus & Borgen (2002) — see
 * research/quality-of-life-rules.md for the full citations and reasoning.
 */
const CATEGORY_AFFINITY_WEIGHTS: Record<CategoryId, PersonalityProfile> = {
	extractive: {
		openness: 0,
		conscientiousness: 1,
		extraversion: 0,
		agreeableness: 0,
		neuroticism: -1,
	},
	industrial: {
		openness: 0,
		conscientiousness: 1,
		extraversion: 0,
		agreeableness: 0,
		neuroticism: -1,
	},
	services: {
		openness: 0,
		conscientiousness: 0,
		extraversion: 1,
		agreeableness: 1,
		neuroticism: 0,
	},
	knowledge: {
		openness: 1,
		conscientiousness: 1,
		extraversion: 0,
		agreeableness: 0,
		neuroticism: 0,
	},
	command: {
		openness: 0,
		conscientiousness: 1,
		extraversion: 1,
		agreeableness: 0,
		neuroticism: -1,
	},
};

function clamp(value: number, min: number, max: number): number {
	return Math.min(max, Math.max(min, value));
}

/**
 * -1..1 similarity between a citizen's personality and a category's ideal
 * profile. Traits are compared as *shares of the citizen's total trait
 * budget* (not absolute point values), since traits are generated by
 * splitting a fixed budget — an average citizen (equal shares) scores 0
 * against every category; emphasizing a category's rewarded traits (or
 * de-emphasizing its penalized ones) scores positive; the reverse scores
 * negative. See research/quality-of-life-rules.md for the model.
 */
function getPersonalitySectorAffinity(
	personality: PersonalityProfile,
	categoryId: CategoryId,
): number {
	const weights = CATEGORY_AFFINITY_WEIGHTS[categoryId];
	const total = TRAITS.reduce((sum, trait) => sum + personality[trait], 0);
	if (!weights || total <= 0) return 0;

	const averageShare = 1 / TRAITS.length;
	const score = TRAITS.reduce((sum, trait) => {
		const share = personality[trait] / total;
		return sum + weights[trait] * (share - averageShare);
	}, 0);

	return clamp(score, -1, 1);
}

export type { PersonalityProfile };
export { CATEGORY_AFFINITY_WEIGHTS, getPersonalitySectorAffinity };
